spring.application.name=sb-ecom

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=noppy7313

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

//????????????
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
project.image=target/classes/static/images
# spring.h2.console.path=/h2-console

//Entity?????????????????SQL????????
#spring.jpa.show-sql=true

spring.app.jwtSecret=myVeryLongSecretKeyForJwtAuthentication1234567890
spring.app.jwtExpirationMs=300000000
spring.ecom.app.jwtCookieName=springBootEcom
